site_name: DemocraCRM
site_url: https://docs.democracrm.org
repo_name: democracrm/democracrm
repo_url: https://github.com/democracrm/democracrm
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
  features:
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/democracrm/democracrm
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/democracrm
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
nav:
    - Introduction: 'index.md'
    - Installation:
      - Installation Overview: 'installation/installation_overview.md'
      - Debian Linux: 'installation/debian_linux.md'
      - PostgreSQL Database: 'installation/postgresql_database.md'
      - DemocraCRM Application: 'installation/democracrm_app.md'
      - Gunicorn: 'installation/gunicorn.md'
      - NGINX Web Server: 'installation/nginx_web_server.md'
    - Configuration: 'configuration.md'
    - Upgrading: 'upgrading.md'
    - Getting Started:
      - User Account: 'getting-started/user_account.md'
      - Organization Account: 'getting-started/organization_account.md'
      - Platform & Campaigns: 'getting-started/platform-campaigns.md'
      - People & Places: 'getting-started/people-places.md'
    - Features:
      - Overview: 'features/overview.md'
      - Accounts: 'features/accounts.md'
      - Contacts: 'features/contacts.md'
      - Places: 'features/places.md'
      - Organizing: 'features/organizing.md'
      - Lobbying: 'features/lobbying.md'
      - Social: 'features/social.md'
      - Web: 'features/web.md'
    - Data Models:
      - Accounts:
        - User Account: 'models/accounts/user_account.md'
        - Organization Account: 'models/accounts/organization_account.md'
      - Core:
        - Geographic Boundaries: 'models/core/geographic_boundaries.md'
      - Organizing:
        - 'models/organizing/campaign.md'
    - Development:
      - URL Scheme: 'development/url_scheme.md'
      - Documentation: 'development/documentation.md'
    - Release Notes
    - Glossary: 'glossary.md'
    - License: 'license.md'
